In [2]:
%cd ..

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import re

In [2]:
data = pd.read_csv(r'data/NYC_Jobs.csv', sep = ',')
pd.set_option('display.max_columns', 999)
print (data.shape)
data['Posting Date'] = data['Posting Date'].astype('datetime64[D]')
data.head(3)

(3207, 27)

,Job ID,Agency,Posting Type,Business Title,Civil Service Title,Title Code No,Level,Job Category,Full-Time/Part-Time indicator,Salary Range From,Salary Range To,Salary Frequency,Work Location,Division/Work Unit,Job Description,Minimum Qual Requirements,Preferred Skills,Additional Information,To Apply,Hours/Shift,Work Location 1,Recruitment Contact,Residency Requirement,Posting Date,Post Until,Posting Updated,Process Date
0,87990,DEPARTMENT OF BUSINESS SERV.,Internal,Account Manager,CONTRACT REVIEWER (OFFICE OF L,40563,1,NaN,NaN,42405.00,65485.00,Annual,110 William St. N Y,Strategy & Analytics,Division of Economic & Financial Opportunity (...,1.\tA baccalaureate degree from an accredited ...,â€¢\tExcellent interpersonal and organizationa...,"Salary range for this position is: $42,405 - $...",NaN,NaN,NaN,NaN,New York City residency is generally required ...,2011-06-24,NaN,06/24/2011,07/02/2019
1,97899,DEPARTMENT OF BUSINESS SERV.,Internal,"EXECUTIVE DIRECTOR, BUSINESS DEVELOPMENT",ADMINISTRATIVE BUSINESS PROMOT,10009,M3,NaN,F,60740.00,162014.00,Annual,110 William St. N Y,Tech Talent Pipeline,The New York City Department of Small Business...,1. A baccalaureate degree from an accredited c...,NaN,NaN,"In addition to applying through this website, ...",NaN,NaN,NaN,New York City residency is generally required ...,2012-01-26,NaN,01/26/2012,07/02/2019
2,132292,NYC HOUSING AUTHORITY,External,Maintenance Worker - Technical Services-Heatin...,MAINTENANCE WORKER,90698,0,Maintenance & Operations,F,51907.68,54580.32,Annual,Heating Mgt-Operations,Management Services Department,"Under direct supervision, assist in the routin...",1. Three years of full-time satisfactory exper...,1. A High School Diploma or GED. 2. CDL Dri...,1. A Motor Vehicle Driverâ€™s License valid i...,"Click the ""Apply Now"" button.",NaN,NaN,NaN,NYCHA has no residency requirements.,2013-10-24,NaN,12/12/2013,07/02/2019

In [3]:
# for preserving numeric type
numeric_columns = []
str_columns = []
for column in data.columns:
    if(data[column].dtype == object):
        str_columns.append(column)
    else:
          numeric_columns.append(column)

In [4]:
#delete excess characters

def remove_char(x):
    x = re.sub(r'[^a-zA-Z0-9 &?!.,-]', '', str(x))
#     x = re.sub(r'[^\w&?!.,]', '', str(x))   deleting spaces
    return x


for col in data[str_columns]:
    data[col] = data[col].apply(remove_char)
data = data.replace('nan', np.NaN)
data.head(3)

,Job ID,Agency,Posting Type,Business Title,Civil Service Title,Title Code No,Level,Job Category,Full-Time/Part-Time indicator,Salary Range From,Salary Range To,Salary Frequency,Work Location,Division/Work Unit,Job Description,Minimum Qual Requirements,Preferred Skills,Additional Information,To Apply,Hours/Shift,Work Location 1,Recruitment Contact,Residency Requirement,Posting Date,Post Until,Posting Updated,Process Date
0,87990,DEPARTMENT OF BUSINESS SERV.,Internal,Account Manager,CONTRACT REVIEWER OFFICE OF L,40563,1,NaN,NaN,42405.00,65485.00,Annual,110 William St. N Y,Strategy & Analytics,Division of Economic & Financial Opportunity D...,1.A baccalaureate degree from an accredited co...,Excellent interpersonal and organizational ski...,"Salary range for this position is 42,405 - 45,...",NaN,NaN,NaN,NaN,New York City residency is generally required ...,2011-06-24,NaN,06242011,07022019
1,97899,DEPARTMENT OF BUSINESS SERV.,Internal,"EXECUTIVE DIRECTOR, BUSINESS DEVELOPMENT",ADMINISTRATIVE BUSINESS PROMOT,10009,M3,NaN,F,60740.00,162014.00,Annual,110 William St. N Y,Tech Talent Pipeline,The New York City Department of Small Business...,1. A baccalaureate degree from an accredited c...,NaN,NaN,"In addition to applying through this website, ...",NaN,NaN,NaN,New York City residency is generally required ...,2012-01-26,NaN,01262012,07022019
2,132292,NYC HOUSING AUTHORITY,External,Maintenance Worker - Technical Services-Heatin...,MAINTENANCE WORKER,90698,0,Maintenance & Operations,F,51907.68,54580.32,Annual,Heating Mgt-Operations,Management Services Department,"Under direct supervision, assist in the routin...",1. Three years of full-time satisfactory exper...,1. A High School Diploma or GED. 2. CDL Dri...,1. A Motor Vehicle Drivers License valid in t...,Click the Apply Now button.,NaN,NaN,NaN,NYCHA has no residency requirements.,2013-10-24,NaN,12122013,07022019

In [5]:
useful_inf = data.drop(["Job ID", "Agency", "Posting Type", "Civil Service Title", "Title Code No", 
                        "Work Location", "Recruitment Contact", "Residency Requirement", "Post Until", 
                        "Posting Updated", "Process Date"], axis=1)

In [42]:
useful_inf.head(3)

,Business Title,Level,Job Category,Full-Time/Part-Time indicator,Salary Range From,Salary Range To,Salary Frequency,Division/Work Unit,Job Description,Minimum Qual Requirements,Preferred Skills,Additional Information,To Apply,Hours/Shift,Work Location 1,Posting Date
0,Account Manager,1,NaN,NaN,42405.00,65485.00,Annual,Strategy & Analytics,Division of Economic & Financial Opportunity D...,1.A baccalaureate degree from an accredited co...,Excellent interpersonal and organizational ski...,"Salary range for this position is 42,405 - 45,...",NaN,NaN,NaN,2011-06-24
1,"EXECUTIVE DIRECTOR, BUSINESS DEVELOPMENT",M3,NaN,F,60740.00,162014.00,Annual,Tech Talent Pipeline,The New York City Department of Small Business...,1. A baccalaureate degree from an accredited c...,NaN,NaN,"In addition to applying through this website, ...",NaN,NaN,2012-01-26
2,Maintenance Worker - Technical Services-Heatin...,0,Maintenance & Operations,F,51907.68,54580.32,Annual,Management Services Department,"Under direct supervision, assist in the routin...",1. Three years of full-time satisfactory exper...,1. A High School Diploma or GED. 2. CDL Dri...,1. A Motor Vehicle Drivers License valid in t...,Click the Apply Now button.,NaN,NaN,2013-10-24